# Generated by Django 3.0.8 on 2020-07-23 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(choices=[('Burnout', 'Burnout'), ('Beginners', 'Beginners'), ('Frameworks', 'Frameworks'), ('Interviews', 'Interviews'), ('JavaScript', 'JavaScript'), ('Programming', 'Programming'), ('Python', 'Python'), ('Soft Skills', 'Soft Skills'), ('Tutorial Hell', 'Tutorial Hell')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('body', models.TextField(max_length=3000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
